In [3]:
# 예제 1. 문자열에서 유니코드 코드포인트 리스트 만들기(버전1)

symbols = "$*&!@"
codes = []

for symbol in symbols :
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [4]:
# 예제 2. 문자열에서 유니코드 코드포인트 리스트 만들기(버전2)

symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [5]:
# 예제 3. 지능형 리스트 지역 변수와 주변 변수 구분 예제

x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
# 예제 4. 지능형 리스트로 만든 리스트

symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [7]:
# 예제 5. map()/filter()로 만든 리스트

symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x000002608629EB30>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [8]:
# 예제 6. 지능형 리스트를 이용한 데카르트 곱

colors = ['black', 'white']
sizes = ['S','M','L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [9]:
# 예제 7. 제너레이터 표현식에서 튜플 초기화하기

symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [10]:
# 예제 7-2. 제너레이터 표현식에서 배열 초기화하기

import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [11]:
# 예제 8. 제너레이터 표현식에서의 데카르트 곱

colors = ['black','white']
sizes = ['S','M','L']

for tshirt in ('{} {}'.format(c,s) for s in sizes for c in colors):
    print(tshirt)

black S
white S
black M
white M
black L
white L


In [13]:
# 예제 9. 레코드로 사용된 튜플1

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo',2003,32450,0.66,8014)
traveler_ids = [('USA','31195855'),
                ('BRA','CE342567'),
                ('ESP','XDA205856')]

for passport in sorted(traveler_ids) :
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0],passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [14]:
# 예제 10. 레코드로 사용된 튜플2

for country, _ in traveler_ids :
    print(country)

USA
BRA
ESP


In [15]:
# 예제 9. 튜플 언패킹

city, year, pop, chg, area = ('Tokyo',2003,32450,0.66,8014)

In [16]:
print('%s/%s'%passport)

USA/31195855


In [17]:
# 예제 11. 튜플 병렬 할당

lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [18]:
# 예제 12. 튜플 병렬 할당(swap)

a = 10; b = 20
b,a = a,b
print(a,b)

20 10


In [19]:
# 예제 13. 튜플 병렬 할당(함수 인수 전달)

divmod(20,8)

(2, 4)

In [20]:
# 예제 13-2

t = (20,8)
divmod(*t)

(2, 4)

In [21]:
# 예제 13-3

quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [22]:
# 예제 14. 파일시스템 경로에서 경로명과 파일명 추출

import os

_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [23]:
# 예제 15. *사용으로 병렬 할당 언패킹1

a,b,*rest = range(5)
a,b,rest

(0, 1, [2, 3, 4])

In [24]:
# 예제 15-2

a,b,*rest = range(3)
a,b,rest

(0, 1, [2])

In [25]:
# 예제 15-3

a,b,*rest = range(2)
a,b,rest

(0, 1, [])

In [26]:
# 예제 16. *사용으로 병렬 할당 언패킹 2

a,*body,c,d = range(5)
a,body,c,d

(0, [1, 2], 3, 4)

In [27]:
# 예제 16-2

*head,b,c,d = range(5)
head,b,c,d

([0, 1], 2, 3, 4)

In [28]:
# 예제 17. longitude에 접근하기 위해 내포된 튜플 언패킹

metro_areas = [
    ("Tokyo","JP",36.933,(35,139)),
    ("Delhi NCR","IN",21,(28,77)),
    ("Mexico City","MX",20,(19,-99)),
    ("New York-Newark","US",20,(40,-74)),
    ("Sao Paulo","BR",19,(-23,-46))
]

print("{:15}|{:^9}|{:^9}".format('','lat.','long.'))
fmt = '{:15}|{:9.4f}|{:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas :
    if longi <= 0:
        print(fmt.format(name, lat, longi))

               |  lat.   |  long.  
Mexico City    |  19.0000| -99.0000
New York-Newark|  40.0000| -74.0000
Sao Paulo      | -23.0000| -46.0000


In [29]:
# 예제 18. 명명된 튜플형을 정의하고 사용하기

from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo','JP',36.933,(35.689,139.691))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))

In [30]:
# 예제 18-2

tokyo.population

36.933

In [31]:
tokyo.coordinates

(35.689, 139.691)

In [32]:
tokyo[1]

'JP'

In [33]:
# 예제 19. 명명된 튜플의 속성과 메서드([예제 18]에 이어서)

City._fields

('name', 'country', 'population', 'coordinates')

In [34]:
LatLong = namedtuple('LatLong','lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613,77.208))

In [35]:
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [36]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [37]:
# 예제 20. 슬라이싱 예제 

l = [10,20,30,40,50,60]
l[:2] # 2번 인덱스에서 분할

[10, 20]

In [38]:
l[2:]

[30, 40, 50, 60]

In [39]:
l[:3]

[10, 20, 30]

In [40]:
l[3:]

[40, 50, 60]

In [41]:
# 예제 21. 단순 텍스트 파일 청구서의 행 항목들

invoice = """
0.....6..................25.......33......40.......
1909  Pimoroni              $17.50   3     $52.50
1489  6mm Tacile            $4.95    2     $9.90
"""

SKU = slice(0,6)
DESRIPTION = slice(6,25)
UNIT_PRICE = slice(25,33)
QUANTITY = slice(33,40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tacile         
 


In [42]:
# 예제 22. 가변 시퀀스 변형

l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
l[2:5] = [20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [44]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [45]:
l[3::2] = [11,22]
l

[0, 1, 20, 11, 5, 22, 9]

In [46]:
# 예제 23. 가변 시퀀스 변형 오류 예시

l[2:5] = 100

TypeError: can only assign an iterable

In [47]:
# 예제 24. 올바른 할당문

l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [48]:
# 예제 25. 시퀀스에 덧셈, 곱셈 수행

l = [1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [49]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [51]:
# 예제 26. 길이가 3인 리스트 3개로 표현한 틱택토 보드

board = [['_'] *3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [52]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [53]:
# 예제 27. 동일한 리스트에 대한 세 개의 참조를 가진 리스트1

weird_board = [['_']*3]*3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [54]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [55]:
# 예제 28. 동일한 리스트에 대한 세 개의 참조를 가진 리스트 2

row = ['_'] * 3
board = []
for i in range(3) :
    board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [56]:
# 예제 29. [예제 26]의 지능형 리스트의 다른 표현

board = []
for i in range(3) :
    row = ['_'] * 3
    board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [57]:
# 예제 30. 가변 시퀀스의 복합 할당
# 연산자 곱 결과

l = [1,2,3]
id(l)

2613622510016

In [58]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [59]:
id(l)

2613622510016

In [60]:
# 예제 31. 불변 시퀀스의 복합 할당
# 연산자 곱 결과

t = (1,2,3)
id(t)

2613591830528

In [61]:
t *= 2
id(t)

2613622468288

In [62]:
# 예제 32. 퀴즈

t = (1,2,[30,40])
print(t)

t[2] += [50,60]

"""
a. t는 (1,2,[30,40,50,60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다'는 
메세지와 함께 TypeError가 발생한다.
c. a와 b 둘 다 틀리다.
d. a와 b 둘 다 맞다.
"""

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [63]:
# 예제 33. 퀴즈 코드 수행 결과

print(t)

(1, 2, [30, 40, 50, 60])


In [64]:
# 예제 34. 리스트 정렬:sorted()

fruits = ['grape','raspberry','apple','banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [65]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [66]:
sorted(fruits, reverse = True)

['raspberry', 'grape', 'banana', 'apple']

In [67]:
sorted(fruits, key = len)

['grape', 'apple', 'banana', 'raspberry']

In [68]:
# 예제 35. 리스트 정렬: list.sort()

sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [69]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [70]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [71]:
# 예제 36. 커다란 실수 배열의 생성

from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.9851258401162116

In [72]:
# 예제 37. 커다란 실수 배열의 저장/로딩

with open('floats.bin', 'wb') as f:
    floats.tofile(f)

In [73]:
floats2 = array('d')

with open('floats.bin', 'rb') as f :
    floats2.fromfile(f, 10**7)

floats2[-1]

0.9851258401162116

In [74]:
floats == floats2

True

In [75]:
# 예제 38. 배열 항목 값의 바이트 중 하나 변경

import array
numbers = array.array('h', [-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)

5

In [76]:
memv[0]

-2

In [77]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [78]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [89]:
pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     -------------------------------- ----- 51.2/59.7 kB 890.4 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 798.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.2/12.9 MB 6.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/12.9 MB 8.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/12.9 MB 11.0 MB/s eta 0:00:02
   ------ --------------------------------- 2.2/12.9 MB 13.9 MB/s eta 0:00:01
   ---------- ----------------------------- 3.5/12.9 MB 17.3 MB/s eta 0:00:01
   --------------- ------------------------ 5.1/12.9 MB 20.5 MB/s eta 0:00:01
   ------------------------- -------------- 8.3/12.9 MB 27.8 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.9 MB 36.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.8/12.9 MB 31.2 MB/s eta 0:00


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [90]:
# 예제 39. numpy.ndarray에서 행과 열을 이용한 기본 연산

import numpy

a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
type(a)

numpy.ndarray

In [93]:
# 예제 40. numpy.ndarray에서 행과 열을 이용한 기본 연산2

a.shape

(12,)

In [94]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
# 예제 41. numpy.ndarray에서 행과 열을 이용한 기본 연산3

a[2]

array([ 8,  9, 10, 11])

In [96]:
a[2,1]

np.int64(9)

In [97]:
a[:,1]

array([1, 5, 9])

In [98]:
# 예제 42. numpy.ndarray에서 행과 열을 이용한 기본연산 4

a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [99]:
# 예제 43. 덱 이용하기 1
from collections import deque
dq = deque(range(10), maxlen = 10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [100]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [101]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [102]:
# 예제 44. 덱 이용하기2

dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [103]:
dq.extend([11,22,33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [104]:
dq.extendleft([10,20,30,40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)